package asd.fgh.minesweeper.persistence;

import asd.fgh.minesweeper.logic.Difficulty;
import java.io.Serializable;

/**
 * Produced from a game instance, describes the result of a game.
 *
 * @author ahv
 */
public class Score implements Serializable {

    private final Difficulty difficulty;
    private final int time;
    public String name;
    private final boolean won;

    /**
     * Score object. Should be generated by a Game instance.
     * @param difficulty Difficulty setting.
     * @param time Time the game took to finish.
     * @param won Whether the game was won or not. True if won.
     */
    public Score(Difficulty difficulty, int time, boolean won) {
        this.difficulty = difficulty;
        this.time = time;
        this.won = won;
    }

    public boolean isWon() {
        return won;
    }

    public Difficulty getDifficulty() {
        return difficulty;
    }

    public int getTime() {
        return time;
    }

    /**
     * Name associated with the score.
     *
     * @return Name or "Unknown" if no name has been entered.
     */
    public String getName() {
        if (name == null) {
            return "Unknown";
        }
        return name;
    }

    // Can only set once.
    /**
     * Set name to associate with score, can be set only once. Will be validated.
     * @param name Name to associate with the score.
     */
    public void setName(String name) {
        if (name == null) {
            // TODO: Validate
            this.name = name;
        }
    }
}
